id: PCCC7CF9C
initial_creation_type: ocr
source_metadata:
  volumes:
    7fa8cc4aee6343d1873431b92fcf3a9f:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: གཤིན་རྗེ་གཤེད་ནག་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
